---
 - yum:
     name: httpd
     state: present

 - template:
     src: index.html.j2
     dest: /var/www/html/index.html

 - lineinfile:
     path: /etc/httpd/conf/httpd.conf
     regexp: '^Listen 80'
     line: 'Listen 8080'
     state: present

 - service:
     name: httpd
     state: started
     enabled: yes

